### ISSUE TITLE
Use along with ECS Orb

### ISSUE THREAD

**Issue by elcidowneador** [CircleCI-Public/aws-parameter-store-orb#10]
### Orb version
1.0.0

### What happened

I can only use along with jobs, but not in a workflow.

### Expected behavior

I'm using ECS Orb with Environment variables set at project level, and i want to source this variables but i don't see the way to use it within workflow, only with jobs. It happens the same with the official Slack Orb.

Is there any way to do? Thanks

**Comment by lokst** [comment]
@elcidowneador Could you provide us with an example `config.yml` so that we can better understand the issue?

**Comment by elcidowneador** [comment]
@lokst, currently i don't own an example, but the goal is to load environment variables into a workflow and not only in a job.

Currently i'm using ECS official Orb and does not need to use any job, everything is inside workflow section, but is not possible to use variables whitin workflow.

**Comment by lokst** [comment]
@elcidowneador Could you configure the jobs in your workflow with `pre-steps` (https://circleci.com/docs/2.0/reusing-config/#using-pre-and-post-steps) that source the variables?
