### ISSUE TITLE
--filters is deprecated, use --parameter-filters instead

### ISSUE THREAD

**Issue by chrisstephenmiller** [CircleCI-Public/aws-parameter-store-orb#12]
### Orb version 

1.0.0

### What happened

https://circleci.com/gh/paroadmin/registration-app/148

SSM values are not retrieved successfully because the '--filters' option is deprecated. Testing the AWS CLI in isolation, there are issues with retrieving values using this option that are resolved by using '--parameter-filters' instead, as per [AWS documentation](https://docs.aws.amazon.com/cli/latest/reference/ssm/describe-parameters.html):

> Options:
> --filters (list)
> This data type is deprecated. Instead, use ParameterFilters

Using '--parameter-filters' also allows for the 'Option' filter (Option=[BeginsWith, Equals, Contains]).

### Expected behavior

SSM values retrieved successfully.

**Comment by parrello** [comment]
I encountered the same! Since there's already an open PR (thanks @chrisstephenmiller) it would be great if this could move forward. Better this than writing a custom command and copy-paste in more than one repo 😁

**Comment by chrisstephenmiller** [comment]
How can we get movement on this? @KyleTryon?

**Comment by chrisstephenmiller** [comment]
Closed by #13.
