### ISSUE TITLE
/tmp/parameterstore/PARAMETERSTORESOURCEFILE: No such file or directory

### ISSUE THREAD

**Issue by CEF-DawnF** [CircleCI-Public/aws-parameter-store-orb#15]
I am attempting to use your orb.  I have a job that calls the below in the steps
- aws-parameter-store/load

However Circle CI reports this error

/tmp/parameterstore/PARAMETERSTORESOURCEFILE: No such file or directory

Prior to running this I am configuring the AWS CLI to assume a role which has administrator privilege (in case that makes a difference)

Your help would be very much appreciated

**Comment by gmemstr** [comment]
@CEF-DawnF It may be worth examining what the command here: https://github.com/CircleCI-Public/aws-parameter-store-orb/blob/master/src/commands/load.yml#L18 returns in your specific instance.
